### PR TITLE
Document how to use persistent connections

### LINKED ISSUE #74: Persistent DB connection (a la `CONN_MAX_AGE`)
Does `django-snowflake` support a persistent DB connection, in the same vein as Django's usual CONN_MAX_AGE?

I tried setting `client_session_keep_alive`, but from what I can glean from the logs the app is still creating and closing a new Snowflake connection for every request.

### PR DESCRIPTION
**Pull request by timgraham**
Fixes #74

### CODE REVIEW

**Comment by eddyojb88** [comment]
Hi @timgraham will this also solve issues like the token authentication token expiration issue?

I am having an issue with my django connection expiring after 4 hours.

**Comment by timgraham** [comment]
I'm not a Snowflake expert, but according to https://community.snowflake.com/s/article/Authentication-token-has-expired-The-user-must-authenticate-again, setting `client_session_keep_alive` might be the solution. Let me know if it works.

**Review by sidmitra — APPROVED** [review]
Seconded. We're using this on prod for the past month and it works well. 

There're still some new log messages like the following we're seeing at certain times.
>This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.

We're still debugging the above. It superficially looked related to connections timing out(but earlier than max-age).

**Comment by eddyojb88** [comment]
Yes I think this works thank you.

**Pull request merged**
